motor_profiles:
  RMD-X4-P36-36:
    short_name: X4
    reduction_ratio: 36
    single_turn_pulses: 16384
    pole_pairs: 11
    max_torque_nm: 34.5
    rated_current_a: 8.625
    max_current_a: 31
    stall_current_a: 30
    max_speed_rpm: 4000
    nominal_speed_rpm: 3000
    position_plan_max_speed_rpm: 996
    position_plan_max_acc_dps_s: 5000
    position_plan_max_dec_dps_s: 5000
    speed_plan_max_acc_dps_s: 5000
    speed_plan_max_dec_dps_s: 5000
    over_voltage_v: 55
    low_voltage_v: 20
    shutdown_temp_c: 100
    resume_temp_c: 90
    kt_out: 1.2
    supports_single_turn_angle: false
    supports_mit: true
    smoke:
      max_normal_speed_dps: 360
      max_normal_delta_deg: 360
      max_normal_abs_deg: 720
      max_speed_dps: 10
      max_delta_deg: 1
      max_abs_deg: 5
      max_current_a: 0.3
      max_torque_nm: 0.2
      max_mit_p_rad: 0.05
      max_mit_delta_joint_deg: 1
      max_mit_target_joint_deg: 180
      max_mit_v_rad_s: 0.2
      max_mit_hz: 500
      max_mit_kp: 50
      max_mit_kd: 2
      max_mit_tau_nm: 24
      max_mit_abort_torque_nm: 10
      max_mit_abort_speed_dps: 360
    source_version: '26042501'
    voltage_sample_res: 21
    enable_ethercat: true
    enable_second_encoder: 1
    outencoder: 1
    outencoder_1: 50
    outencoder_2: 2
    outencoder_3: 1
    outencoder2_1: 0
    outencoder2_2: 1
    outencoder2_3: 0
    current_sample_res_mohm: 5
    exchange_phase: false
    change_motor_direction: false
    calibrat_current_a: 2
    select_thermistor: 0
    encoder_abnormal_value: 100
    encoder_abnormal_speed: 5
    automatic_error_recovery: true
    pid:
      position_kp: 0.05
      position_ki: 0.0
      position_kd: 0.5
      position_t_filter: 0.0001
      speed_kp: 0.01
      speed_ki: 0.0001
      speed_t_filter: 0.0005
      q_current_kp: 1.5
      q_current_ki: 0.05
      q_current_t_filter: 0.0005
      d_current_kp: 1.5
      d_current_ki: 0.05
      d_current_t_filter: 0.0005
      position_r_slope: 0.0
      speed_kd: 0.0
      speed_r_slope: 0.0
      q_current_kd: 0.0
      q_current_r_slope: 0.0
      d_current_kd: 0.0
      d_current_r_slope: 0.0
  RMD-X6-P20-60:
    short_name: X6
    reduction_ratio: 19.61
    single_turn_pulses: 16384
    pole_pairs: 10
    max_torque_nm: 60
    rated_current_a: 13.4
    max_current_a: 42
    stall_current_a: 40
    max_speed_rpm: 4000
    nominal_speed_rpm: 3000
    position_plan_max_speed_rpm: 996
    position_plan_max_acc_dps_s: 5000
    position_plan_max_dec_dps_s: 5000
    speed_plan_max_acc_dps_s: 5000
    speed_plan_max_dec_dps_s: 5000
    over_voltage_v: 55
    low_voltage_v: 20
    shutdown_temp_c: 100
    resume_temp_c: 90
    kt_out: 1.5
    supports_single_turn_angle: false
    supports_mit: true
    smoke:
      max_normal_speed_dps: 360
      max_normal_delta_deg: 360
      max_normal_abs_deg: 720
      max_speed_dps: 10
      max_delta_deg: 1
      max_abs_deg: 5
      max_current_a: 0.4
      max_torque_nm: 0.3
      max_mit_p_rad: 0.05
      max_mit_delta_joint_deg: 1
      max_mit_target_joint_deg: 180
      max_mit_v_rad_s: 0.2
      max_mit_hz: 500
      max_mit_kp: 50
      max_mit_kd: 2
      max_mit_tau_nm: 24
      max_mit_abort_torque_nm: 15
      max_mit_abort_speed_dps: 360
    source_version: '26042501'
    voltage_sample_res: 21
    enable_ethercat: true
    enable_second_encoder: 3
    outencoder: 1
    outencoder_1: 40
    outencoder_2: 2
    outencoder_3: 0
    outencoder2_1: 0
    outencoder2_2: 2
    outencoder2_3: 0
    current_sample_res_mohm: 3
    exchange_phase: false
    change_motor_direction: false
    calibrat_current_a: 2.5
    select_thermistor: 1
    encoder_abnormal_value: 100
    encoder_abnormal_speed: 5
    automatic_error_recovery: true
    pid:
      position_kp: 0.06
      position_ki: 0.0
      position_kd: 0.5
      position_t_filter: 0.0001
      speed_kp: 0.01
      speed_ki: 0.0001
      speed_t_filter: 0.005
      q_current_kp: 0.5
      q_current_ki: 0.05
      q_current_t_filter: 0.0001
      d_current_kp: 0.5
      d_current_ki: 0.05
      d_current_t_filter: 0.0001
      position_r_slope: 0.0
      speed_kd: 0.0
      speed_r_slope: 0.0
      q_current_kd: 0.0
      q_current_r_slope: 0.0
      d_current_kd: 0.0
      d_current_r_slope: 0.0
  RMD-X8-P20-120:
    short_name: X8
    reduction_ratio: 19.61
    single_turn_pulses: 16384
    pole_pairs: 10
    max_torque_nm: 129
    rated_current_a: 24.88
    max_current_a: 64
    stall_current_a: 61.9
    max_speed_rpm: 3500
    nominal_speed_rpm: 2490
    position_plan_max_speed_rpm: 996
    position_plan_max_acc_dps_s: 5000
    position_plan_max_dec_dps_s: 5000
    speed_plan_max_acc_dps_s: 5000
    speed_plan_max_dec_dps_s: 5000
    over_voltage_v: 55
    low_voltage_v: 20
    shutdown_temp_c: 100
    resume_temp_c: 90
    kt_out: 2.0
    supports_single_turn_angle: false
    supports_mit: true
    smoke:
      max_normal_speed_dps: 360
      max_normal_delta_deg: 360
      max_normal_abs_deg: 720
      max_speed_dps: 10
      max_delta_deg: 1
      max_abs_deg: 5
      max_current_a: 0.5
      max_torque_nm: 0.4
      max_mit_p_rad: 0.05
      max_mit_delta_joint_deg: 1
      max_mit_target_joint_deg: 180
      max_mit_v_rad_s: 0.2
      max_mit_hz: 500
      max_mit_kp: 50
      max_mit_kd: 2
      max_mit_tau_nm: 24
      max_mit_abort_torque_nm: 25
      max_mit_abort_speed_dps: 360
    source_version: '26042501'
    voltage_sample_res: 21
    enable_ethercat: true
    enable_second_encoder: 3
    outencoder: 1
    outencoder_1: 40
    outencoder_2: 2
    outencoder_3: 0
    outencoder2_1: 0
    outencoder2_2: 2
    outencoder2_3: 0
    current_sample_res_mohm: 2
    exchange_phase: false
    change_motor_direction: false
    calibrat_current_a: 2.5
    select_thermistor: 1
    encoder_abnormal_value: 100
    encoder_abnormal_speed: 5
    automatic_error_recovery: true
    pid:
      position_kp: 0.008
      position_ki: 0.0
      position_kd: 0.1
      position_t_filter: 0.0001
      speed_kp: 0.03
      speed_ki: 0.0001
      speed_t_filter: 0.005
      q_current_kp: 0.8
      q_current_ki: 0.08
      q_current_t_filter: 0.0001
      d_current_kp: 0.8
      d_current_ki: 0.08
      d_current_t_filter: 0.0001
      position_r_slope: 0.0
      speed_kd: 0.0
      speed_r_slope: 0.0
      q_current_kd: 0.0
      q_current_r_slope: 0.0
      d_current_kd: 0.0
      d_current_r_slope: 0.0
  RMD-X12-P20-320:
    short_name: X12
    reduction_ratio: 20
    single_turn_pulses: 16384
    pole_pairs: 20
    max_torque_nm: 300
    rated_current_a: 42.42
    max_current_a: 110
    stall_current_a: 106
    max_speed_rpm: 3000
    nominal_speed_rpm: 2000
    position_plan_max_speed_rpm: 1000
    position_plan_max_acc_dps_s: 5000
    position_plan_max_dec_dps_s: 5000
    speed_plan_max_acc_dps_s: 5000
    speed_plan_max_dec_dps_s: 5000
    over_voltage_v: 70
    low_voltage_v: 20
    shutdown_temp_c: 100
    resume_temp_c: 90
    kt_out: 2.81
    supports_single_turn_angle: false
    supports_mit: true
    smoke:
      max_normal_speed_dps: 360
      max_normal_delta_deg: 360
      max_normal_abs_deg: 720
      max_speed_dps: 10
      max_delta_deg: 1
      max_abs_deg: 5
      max_current_a: 0.5
      max_torque_nm: 0.5
      max_mit_p_rad: 0.05
      max_mit_delta_joint_deg: 1
      max_mit_target_joint_deg: 180
      max_mit_v_rad_s: 0.2
      max_mit_hz: 500
      max_mit_kp: 50
      max_mit_kd: 2
      max_mit_tau_nm: 24
      max_mit_abort_torque_nm: 60
      max_mit_abort_speed_dps: 360
    source_version: '26042501'
    voltage_sample_res: 28
    enable_ethercat: true
    enable_second_encoder: 3
    outencoder: 1
    outencoder_1: 40
    outencoder_2: 1
    outencoder_3: 1
    outencoder2_1: 0
    outencoder2_2: 2
    outencoder2_3: 0
    current_sample_res_mohm: 1
    exchange_phase: null
    change_motor_direction: false
    calibrat_current_a: 3.5
    select_thermistor: 0
    encoder_abnormal_value: 150
    encoder_abnormal_speed: 5
    automatic_error_recovery: true
    pid:
      position_kp: 0.015
      position_ki: 0.0
      position_kd: 0.1
      position_t_filter: 0.0001
      speed_kp: 0.03
      speed_ki: 0.0001
      speed_t_filter: 0.003
      q_current_kp: 0.314
      q_current_ki: 0.01
      q_current_t_filter: 0.003
      d_current_kp: 0.314
      d_current_ki: 0.01
      d_current_t_filter: 0.003
      position_r_slope: 0.0
      speed_kd: 0.0
      speed_r_slope: 0.0
      q_current_kd: 0.0
      q_current_r_slope: 0.0
      d_current_kd: 0.0
      d_current_r_slope: 0.0
  RMD-X15-P20-450:
    short_name: X15
    reduction_ratio: 20.25
    single_turn_pulses: 16384
    pole_pairs: 20
    max_torque_nm: 435
    rated_current_a: 35.35
    max_current_a: 100
    stall_current_a: 95
    max_speed_rpm: 2985
    nominal_speed_rpm: 1985
    position_plan_max_speed_rpm: 1500
    position_plan_max_acc_dps_s: 5000
    position_plan_max_dec_dps_s: 5000
    speed_plan_max_acc_dps_s: 5000
    speed_plan_max_dec_dps_s: 5000
    over_voltage_v: 80
    low_voltage_v: 20
    shutdown_temp_c: 100
    resume_temp_c: 90
    kt_out: 4.579
    supports_single_turn_angle: false
    supports_mit: true
    smoke:
      max_normal_speed_dps: 360
      max_normal_delta_deg: 360
      max_normal_abs_deg: 720
      max_speed_dps: 8
      max_delta_deg: 1
      max_abs_deg: 5
      max_current_a: 0.5
      max_torque_nm: 0.5
      max_mit_p_rad: 0.05
      max_mit_delta_joint_deg: 1
      max_mit_target_joint_deg: 180
      max_mit_v_rad_s: 0.2
      max_mit_hz: 500
      max_mit_kp: 50
      max_mit_kd: 2
      max_mit_tau_nm: 24
      max_mit_abort_torque_nm: 80
      max_mit_abort_speed_dps: 360
    source_version: '26042501'
    voltage_sample_res: 28
    enable_ethercat: true
    enable_second_encoder: 3
    outencoder: 1
    outencoder_1: 60
    outencoder_2: 2
    outencoder_3: 0
    outencoder2_1: 2
    outencoder2_2: 2
    outencoder2_3: 0
    current_sample_res_mohm: 1
    exchange_phase: false
    change_motor_direction: false
    calibrat_current_a: 3
    select_thermistor: 0
    encoder_abnormal_value: 100
    encoder_abnormal_speed: 5
    automatic_error_recovery: true
    pid:
      position_kp: 0.0199999996
      position_ki: 0.0
      position_kd: 0.04
      position_t_filter: 0.0001
      speed_kp: 0.00999999978
      speed_ki: 0.0001
      speed_t_filter: 0.00200000009
      q_current_kp: 0.8792
      q_current_ki: 0.0143
      q_current_t_filter: 0.005
      d_current_kp: 0.8792
      d_current_ki: 0.0143
      d_current_t_filter: 0.005
      position_r_slope: 0.0
      speed_kd: 0.0
      speed_r_slope: 0.0
      q_current_kd: 0.0
      q_current_r_slope: 0.0
      d_current_kd: 0.0
      d_current_r_slope: 0.0
